name: project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  freezed_annotation: ^2.4.1
  dev: ^1.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  firebase: ^9.0.3
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  google_fonts: ^4.0.4
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  flutter_signature_pad: ^3.0.1
  flip_card: ^0.7.0
  flutter_markdown: ^0.6.20
  audioplayers: ^6.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/images/characters/
    - assets/images/fractions/
    - assets/images/howToPlay/
    - assets/images/main_menu/
    - assets/images/flags/
    - assets/icons/
    - assets/tutorial/
    - assets/tutorial/pl_PL/
    - assets/audio/

