// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkgyUmKLWkxfD7A-GoYUfE8RkiOGrYYCE',
    appId: '1:123000223722:web:d61747a3ae69d7e757a493',
    messagingSenderId: '123000223722',
    projectId: 'mafia-30dfa',
    authDomain: 'mafia-30dfa.firebaseapp.com',
    storageBucket: 'mafia-30dfa.appspot.com',
    measurementId: 'G-YRR08RYN7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrIvWupx7oAvLKuXlDj9k_4hqHWX7zIZE',
    appId: '1:123000223722:android:f74b068e4c087c1a57a493',
    messagingSenderId: '123000223722',
    projectId: 'mafia-30dfa',
    storageBucket: 'mafia-30dfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YpjWTPRiGqkBfC_797E5vm7QDQR72qA',
    appId: '1:123000223722:ios:7d3124fdf7e6935457a493',
    messagingSenderId: '123000223722',
    projectId: 'mafia-30dfa',
    storageBucket: 'mafia-30dfa.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
